// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordStoreManagerModule.DAL.Context;

#nullable disable

namespace RecordStoreManagerModule.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecordStoreManagerModule.DAL.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("RecordStoreManagerModule.DAL.Entities.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "The Beatles",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "Abbey Road",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1969, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Artist = "Michael Jackson",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 15.0,
                            IsOnSale = true,
                            Name = "Thriller",
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1982, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Artist = "AC/DC",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "Back in Black",
                            Price = 18.99m,
                            ReleaseDate = new DateTime(1980, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Pink Floyd",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 20.0,
                            IsOnSale = true,
                            Name = "Dark Side of the Moon",
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1973, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Eagles",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "Hotel California",
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1976, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Bruce Springsteen",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "Born in the USA",
                            Price = 17.99m,
                            ReleaseDate = new DateTime(1984, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Fleetwood Mac",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            IsOnSale = true,
                            Name = "Rumours",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(1977, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Nirvana",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 12.5,
                            IsOnSale = true,
                            Name = "Nevermind",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1991, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Led Zeppelin",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "Led Zeppelin IV",
                            Price = 25.99m,
                            ReleaseDate = new DateTime(1971, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Pink Floyd",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 7.5,
                            IsOnSale = true,
                            Name = "The Wall",
                            Price = 24.99m,
                            ReleaseDate = new DateTime(1979, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Adele",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            IsOnSale = true,
                            Name = "21",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(2011, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Artist = "Taylor Swift",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "1989",
                            Price = 22.99m,
                            ReleaseDate = new DateTime(2014, 10, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Queen",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 15.0,
                            IsOnSale = true,
                            Name = "A Night at the Opera",
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1975, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Artist = "Prince",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            IsOnSale = true,
                            Name = "Purple Rain",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1984, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Artist = "The Beatles",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "The Beatles (White Album)",
                            Price = 23.99m,
                            ReleaseDate = new DateTime(1968, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Artist = "Green Day",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "American Idiot",
                            Price = 18.99m,
                            ReleaseDate = new DateTime(2004, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Artist = "Radiohead",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 8.0,
                            IsOnSale = true,
                            Name = "OK Computer",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(1997, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Artist = "Eminem",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 12.0,
                            IsOnSale = true,
                            Name = "The Eminem Show",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2002, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Artist = "Linkin Park",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            IsOnSale = true,
                            Name = "Hybrid Theory",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(2000, 10, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Artist = "Michael Jackson",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "Bad",
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1987, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            Artist = "Black Sabbath",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 7.5,
                            IsOnSale = true,
                            Name = "Paranoid",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(1970, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            Artist = "Green Day",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "Dookie",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(1994, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            Artist = "Guns N' Roses",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 15.0,
                            IsOnSale = true,
                            Name = "Appetite for Destruction",
                            Price = 21.99m,
                            ReleaseDate = new DateTime(1987, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            Artist = "Sam Smith",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "In the Lonely Hour",
                            Price = 18.99m,
                            ReleaseDate = new DateTime(2014, 5, 26, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            Artist = "Kendrick Lamar",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 5.0,
                            IsOnSale = true,
                            Name = "DAMN.",
                            Price = 21.99m,
                            ReleaseDate = new DateTime(2017, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            Artist = "Drake",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 8.0,
                            IsOnSale = true,
                            Name = "Take Care",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2011, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            Artist = "Lauryn Hill",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 12.5,
                            IsOnSale = true,
                            Name = "The Miseducation of Lauryn Hill",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(1998, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            Artist = "U2",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 7.0,
                            IsOnSale = true,
                            Name = "The Joshua Tree",
                            Price = 22.99m,
                            ReleaseDate = new DateTime(1987, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            Artist = "Taylor Swift",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 0.0,
                            IsOnSale = false,
                            Name = "Folklore",
                            Price = 19.99m,
                            ReleaseDate = new DateTime(2020, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            Artist = "Lorde",
                            CreatedDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Discount = 10.0,
                            IsOnSale = true,
                            Name = "Melodrama",
                            Price = 20.99m,
                            ReleaseDate = new DateTime(2017, 6, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
